server:
  port: 8081
spring:
  application:
    name: lab02

  datasource:
    druid:
      url: jdbc:mysql://10.10.64.115/asset-org?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: purang
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 50
      maxWait: 3000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      default-auto-commit: true
  redis:
    database: 0
    host: 10.10.96.142
    port: 6379
    #    password:
    timeout: 5000
    #jedis 配置
    lettuce:
      pool:
        max-active: 20
        max-wait: 10000
        max-idle: 5
        min-idle: 0

mybatis-plus:
  type-aliases-package: com.tsshare.lab02.entity
  mapper-locations: classpath:/mybatis/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
  #      logic-delete-value: 1
  #      logic-not-delete-value: 0
  configuration:
    jdbc-type-for-null: 'null'
    cache-enabled: false
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
